# Introduction

This document should serve as a basic primer for new political science students coming into the program at UNLV. In it, I will cover some basic math concepts that are important for understanding probability, statistics, and research design in general. I will also cover some basic research concepts that are important for conducting quantitative research--whether you're interested in international relations, comparative politics, or American politics.

Given the variation in incoming students' exposure to math and research, I will start with the very basics and build up from there. If you're already familiar with some of the concepts I cover, feel free to skip ahead. There might also be some concepts I cover that might not be absolutely necessary. For those concepts that likely won't be covered in PSC 701 or 702, I'll add an asterisk (\*) to the section title to indicate that it's optional material.

The only background in math I assume will be basic arithmetic. While I won't go too in-depth into the types of math, I'll provide as much context as I can to help you be more fluent in these concepts as you move forward in your studies. In other words, this isn't a probability or statistics textbook, but rather a primer to help you understand the concepts you'll encounter in your classes. Where possible, I'll point you to resources that can help you learn more about these concepts if they interest you.

Importantly, remember that these things take time to learn. Don't get discouraged if you don't understand everything right away. We all struggle with these things at some point, so it's okay to not understand and it's okay to ask for help. The important thing is to keep trying and to keep learning!

## Why Math and Research?

Before I delve into the specifics, it's worth addressing a common question/comment people have when they first encounter math and quantitative research in political science: "Why do I need to learn this?" Or, for the more perplexed, "Since when is there math in political science? I thought this was about politics!"

These are fair questions to ask. After all, political science has a reputation for not being very math-y. But the reality is that math and statistics are essential parts of the discipline--especially in recent decades. Some people will tell you about the "positivist turn in political science"[^1] that happened in the 1950s and 1960s, but that's not really the point I want to make here. The point is that math and statistics are tools that help us understand the world around us. They allow us to make informed inferences about social and political phenomena. Moreover, they help us understand the limitations of our knowledge and the uncertainty that comes with it. In short, math and statistics are tools that help us be better researchers, and they allow us to communicate our findings in a precise and informative manner.

[^1]: For more information about what I mean by this, feel free to ask your professors in class. I'll eventually get to putting a citation here that better explains what I'm referring to.

So, while it might seem daunting at first, learning math and statistics is an essential part of becoming a political scientist. It's not just about learning the tools, but also about learning how to think about the world in a more systematic and rigorous way. And, as you'll see, it can also be a lot of fun!